### ISSUE TITLE
DB에서 칸 번호를 받아오지 말고 칸 위치를 받아오는게 좋아보임

### ISSUE THREAD

**Issue by g5py** [CreNU/librARy-unity#2]
칸 번호를 받아서 위치를 표시하려면,
사용자 폰에 칸 위치를 저장해놓은 Vector3 배열을 만들어야하는데
책장 하나만 해도 66개의 Vector3 객체가 필요함.
스마트폰에서 이런 데이터를 저장하는건 낭비같아보임.
차라리 DB에 칸 위치를 저장하고 사용자 폰에 좌표 하나를 보내주는게 좋아보여

**Comment by g5py** [comment]
계산 해보니까 전주시에 있는 도서관 다합쳐도 1mb도 안나올듯. 파일입출력으로 하면 될거같다

**Comment by deunlee** [comment]
한 칸의 간격이 얼마인지 아니까
Vector3 하나만 만들고 적당히 더하고 빼서 위치 찾는 방법은 어떰?

**Comment by g5py** [comment]
> 한 칸의 간격이 얼마인지 아니까
> Vector3 하나만 만들고 적당히 더하고 빼서 위치 찾는 방법은 어떰?

그 방법도 괜찮아 보이는데 책장 한 면에서 반대쪽 면으로 넘어갈 떄 어떻게 더해야할지 생각해봐야될듯. 기준점을 한 면에 하나씩 둔다던가

**Comment by deunlee** [comment]
한 칸의 depth만큼 더하면 될거 같음.

그리고
> 차라리 DB에 칸 위치를 저장하고 사용자 폰에 좌표 하나를 보내주는게 좋아보여

좌표를 클라이언트에 두던지 서버에 두던지 66 * 2 * 책장수 만큼 하드코딩하는건 아닌거 같음.
서버/클라 어디에서 처리하던지 계산하는 방법이 좋은거 같음
